import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-questrial bg-slate-600 text-slate-100
       container mx-auto p-4 text-4xl`}>
        <main>
          {/* <nav className='flex flex-row justify-around text-2xl'>
            <Link href="/">Home</Link>
            <Link href="/notes">Notes</Link>
          </nav> */}
          {children}
        </main>
      </body>
    </html>
  )
}
